/* import { ExampleKeys } from "website/component-examples"; */

export default {
  title: "Sandbox for komponent",
  name: "ds_code_sandbox",
  type: "document",
  fields: [
    {
      title: "Tittel",
      name: "title",
      type: "string",
      validation: (Rule) =>
        Rule.required().error("Må legge til en enkel tittel"),
    },
    {
      title: "Navn på sandbox",
      description: "Alle sanboxes kan finnes under /sandbox på nettsiden",
      name: "preview",
      type: "string",
      validation: (Rule) =>
        Rule.required().error("Må legge til en navn på sandbox"),
    },
    {
      title: "Sier om navnet er autegenerert",
      name: "autogenerated",
      type: "boolean",
      initialValue: false,
      hidden: true,
    },
  ],
  preview: {
    select: {
      title: "title",
      autogenerated: "autogenerated",
    },
    prepare(selection) {
      const { title, autogenerated } = selection;
      return {
        title: title,
        subtitle: autogenerated ? "Autogenerert" : "",
        media: () => "</>",
      };
    },
  },
};
