import type {
  SanityReference,
  SanityKeyedReference,
  SanityAsset,
  SanityImage,
  SanityFile,
  SanityGeoPoint,
  SanityBlock,
  SanityDocument,
  SanityImageCrop,
  SanityImageHotspot,
  SanityKeyed,
  SanityImageAsset,
  SanityImageMetadata,
  SanityImageDimensions,
  SanityImagePalette,
  SanityImagePaletteSwatch,
} from "sanity-codegen";

export type {
  SanityReference,
  SanityKeyedReference,
  SanityAsset,
  SanityImage,
  SanityFile,
  SanityGeoPoint,
  SanityBlock,
  SanityDocument,
  SanityImageCrop,
  SanityImageHotspot,
  SanityKeyed,
  SanityImageAsset,
  SanityImageMetadata,
  SanityImageDimensions,
  SanityImagePalette,
  SanityImagePaletteSwatch,
};

/**
 * Forside
 *
 *
 */
export interface VkFrontpage extends SanityDocument {
  _type: "vk_frontpage";

  /**
   * Tittel — `string`
   *
   *
   */
  title?: string;

  /**
   * Beskrivelse — `riktekst`
   *
   *
   */
  beskrivelse?: Riktekst;
}

/**
 * Team
 *
 *
 */
export interface Team extends SanityDocument {
  _type: "team";

  /**
   * Navn — `string`
   *
   *
   */
  title?: string;
}

/**
 * Redaktører
 *
 *
 */
export interface Editor extends SanityDocument {
  _type: "editor";

  /**
   * Navn — `string`
   *
   *
   */
  title?: string;

  /**
   * Team — `array`
   *
   *
   */
  teams?: Array<SanityKeyedReference<Team>>;

  /**
   * Sanity bruker-id — `slug`
   *
   *
   */
  user_id?: { _type: "user_id"; current: string };

  /**
   * Profil — `string`
   *
   *
   */
  profile_page?: string;
}

/**
 * Navigation
 *
 *
 */
export interface Navigation extends SanityDocument {
  _type: "navigation";

  /**
   * Tittel — `string`
   *
   *
   */
  title?: string;

  /**
   * Sidemeny — `array`
   *
   * Linker eller dropdowns med linker. Maks dybde på 2 dropdowns er støttet. Sider må være publisert før de kan linkes her.
   */
  sidemenu?: Array<
    SanityKeyed<NavigationDropdown> | SanityKeyed<NavigationLink>
  >;
}

/**
 * Velkommen!
 *
 *
 */
export interface Introduction extends SanityDocument {
  _type: "introduction";

  /**
   * Navn — `string`
   *
   *
   */
  title?: string;

  /**
   * Intro — `string`
   *
   *
   */
  view?: string;
}

/**
 * Changelog
 *
 *
 */
export interface DsChangelog extends SanityDocument {
  _type: "ds_changelog";

  /**
   * Tittel — `string`
   *
   *
   */
  title?: string;

  /**
   * Dato — `date`
   *
   * Endringer sortes basert på datoen gitt her
   */
  change_date?: string;

  /**
   * Pull request (optional) — `url`
   *
   * Eks: https://github.com/navikt/nav-frontend-moduler/pull/1382
   */
  pull_request?: string;

  /**
   * Pakker og versioner — `array`
   *
   *
   */
  packages?: Array<
    SanityKeyed<{
      _type: "package_versions";
      /**
       * Pakke — `reference`
       *
       *
       */
      pack?: SanityReference<DsPackage>;

      /**
       * Semver versjon — `string`
       *
       *
       */
      version?: string;
    }>
  >;

  /**
   * Type endring — `string`
   *
   *
   */
  change?: "new" | "bug" | "breaking" | "uu" | "fix";

  /**
   * Tags — `array`
   *
   * Eks: Button, Alert, All etc
   */
  tags?: Array<SanityKeyed<string>>;

  /**
   * Tekst — `riktekst`
   *
   * Beskrivelse av endringen
   */
  body?: Riktekst;
}

/**
 * Kode med eksempel
 *
 *
 */
export interface DsCodeExample extends SanityDocument {
  _type: "ds_code_example";

  /**
   * Tittel — `string`
   *
   *
   */
  title?: string;

  /**
   * Lenke til eksempel — `url`
   *
   * Alle eksempler kan finnes under /examples på nettsiden
   */
  preview?: string;

  /**
   * Hent kode automatisk fra selve eksemplet? — `boolean`
   *
   * Prøver å hente React og HTML kode automatisk fra storybook
   */
  infercode?: boolean;

  /**
   * Setter om koden er autegenerert — `boolean`
   *
   *
   */
  autogenerated?: boolean;

  /**
   * Kode — `array`
   *
   *
   */
  tabs?: Array<SanityKeyed<CodeExampleExample>>;

  /**
   * Lenke til github-kode (optional) — `url`
   *
   *
   */
  github?: string;
}

/**
 * Sandbox for komponent
 *
 *
 */
export interface DsCodeSandbox extends SanityDocument {
  _type: "ds_code_sandbox";

  /**
   * Tittel — `string`
   *
   *
   */
  title?: string;

  /**
   * Sier om navnet er autegenerert — `boolean`
   *
   *
   */
  autogenerated?: boolean;
}

/**
 * Fargekategori
 *
 *
 */
export interface DsColorCategories extends SanityDocument {
  _type: "ds_color_categories";

  /**
   * Tittel — `string`
   *
   *
   */
  title?: string;

  /**
   * Beskrivelse — `riktekst_enkel`
   *
   *
   */
  description?: RiktekstEnkel;

  /**
   * Farger — `array`
   *
   *
   */
  colors?: Array<SanityKeyed<DsColor>>;
}

/**
 * Autogenerert Propdata
 *
 *
 */
export interface DsProps extends SanityDocument {
  _type: "ds_props";

  /**
   * Tittel — `string`
   *
   *
   */
  title?: string;

  /**
   * Displayname — `string`
   *
   *
   */
  displayname?: string;

  /**
   * Filepath — `string`
   *
   *
   */
  filepath?: string;

  /**
   * props — `array`
   *
   *
   */
  proplist?: Array<
    SanityKeyed<{
      _type: "prop";
      /**
       * Name — `string`
       *
       *
       */
      name?: string;

      /**
       * DefaultValue — `string`
       *
       *
       */
      defaultValue?: string;

      /**
       * Description — `string`
       *
       *
       */
      description?: string;

      /**
       * Required — `boolean`
       *
       *
       */
      required?: boolean;

      /**
       * Type — `string`
       *
       *
       */
      type?: string;

      /**
       * isRef — `boolean`
       *
       *
       */
      ref?: boolean;
    }>
  >;
}

/**
 * Komponentartikkel
 *
 *
 */
export interface DsComponentPage extends SanityDocument {
  _type: "ds_component_page";

  /**
   * Redaktør/kontakt — `reference`
   *
   *
   */
  contact?: SanityReference<Editor>;

  /**
   * Bidragsytere — `array`
   *
   * Legg til de som har bidratt med denne siden!
   */
  contributors?: Array<SanityKeyedReference<Editor>>;

  /**
   * Sidetittel — `string`
   *
   * Bruk en kort og konsis tittel om mulig. Blir satt som `<H1 />` på toppen av siden i URL.
   */
  heading?: string;

  /**
   * url — `slug`
   *
   * Strukturen bestemmes ikke av URL-en
   */
  slug?: { _type: "slug"; current: string };

  /**
   * Bruk-tab — `blockContent`
   *
   *
   */
  usage?: BlockContent;

  /**
   * Design-tab — `blockContent`
   *
   *
   */
  design?: BlockContent;

  /**
   * Utvikling-tab — `blockContent`
   *
   *
   */
  development?: BlockContent;

  /**
   * Tilgjengelighet-tab — `blockContent`
   *
   *
   */
  accessibility?: BlockContent;

  /**
   * Koblet kodepakke — `reference`
   *
   * Kobler komponenten til en pakke
   */
  linked_package?: SanityReference<DsPackage>;

  /**
   * Figma lenke (optional) — `url`
   *
   *
   */
  figma_link?: string;

  /**
   * Tilbakemeldinger — `object`
   *
   *
   */
  metadata_feedback?: {
    _type: "metadata_feedback";
    /**
     * Skjul artikkel feedback modul — `boolean`
     *
     * Gjemmer <<Var denne artikkelen til hjelp?>> modulen.
     */
    hide_feedback?: boolean;
  };
}

/**
 * Komponentartikkel-template
 *
 *
 */
export interface DsComponentTemplate extends SanityDocument {
  _type: "ds_component_template";

  /**
   * Bidragsytere — `array`
   *
   * Legg til de som har bidratt med denne siden!
   */
  contributors?: Array<SanityKeyedReference<Editor>>;

  /**
   * Sidetittel — `string`
   *
   * Bruk en kort og konsis tittel om mulig. Blir satt som `<H1 />` på toppen av siden i URL.
   */
  heading?: string;

  /**
   * url — `slug`
   *
   * Strukturen bestemmes ikke av URL-en
   */
  slug?: { _type: "slug"; current: string };

  /**
   * Bruk — `array`
   *
   *
   */
  content_bruk?: Array<
    | SanityKeyed<GeneriskSeksjon>
    | SanityKeyed<IntroKomponentSeksjon>
    | SanityKeyed<LiveDemoSeksjon>
    | SanityKeyed<UuSeksjon>
    | SanityKeyed<AnatomiSeksjon>
    | SanityKeyed<Tips>
    | SanityKeyed<RelatertInnhold>
  >;

  /**
   * Kode — `array`
   *
   *
   */
  content_kode?: Array<
    | SanityKeyed<GeneriskSeksjon>
    | SanityKeyed<InstallasjonSeksjon>
    | SanityKeyed<PropsSeksjon>
    | SanityKeyed<Tips>
    | SanityKeyed<RelatertInnhold>
  >;

  /**
   * Koblet kodepakke — `reference`
   *
   * Kobler komponenten til en pakke
   */
  linked_package?: SanityReference<DsPackage>;

  /**
   * Figma lenke (optional) — `url`
   *
   *
   */
  figma_link?: string;

  /**
   * Tilbakemeldinger — `object`
   *
   *
   */
  metadata_feedback?: {
    _type: "metadata_feedback";
    /**
     * Skjul artikkel feedback modul — `boolean`
     *
     * Gjemmer <<Var denne artikkelen til hjelp?>> modulen.
     */
    hide_feedback?: boolean;
  };
}

/**
 * Forside
 *
 *
 */
export interface DsFrontpage extends SanityDocument {
  _type: "ds_frontpage";

  /**
   * Innhold — `riktekst_enkel`
   *
   *
   */
  body?: RiktekstEnkel;

  /**
   * Cards — `array`
   *
   *
   */
  cards?: Array<
    SanityKeyed<{
      _type: "card";
      /**
       * Lenke — `reference`
       *
       *
       */
      link_ref?: SanityReference<
        DsComponentPage | KomponentArtikkel | DsArtikkel
      >;

      /**
       * Tittel — `string`
       *
       *
       */
      title?: string;

      /**
       * Innhold — `string`
       *
       *
       */
      content?: string;
    }>
  >;
}

/**
 * Hovedkategorier
 *
 *
 */
export interface MainCategories extends SanityDocument {
  _type: "main_categories";

  /**
   * Tittel — `string`
   *
   *
   */
  title?: string;

  /**
   * Nivå — `string`
   *
   *
   */
  level?: "top" | "designsystem";

  /**
   * Pictogram — `image`
   *
   *
   */
  picture?: {
    _type: "image";
    asset: SanityReference<SanityImageAsset>;
    crop?: SanityImageCrop;
    hotspot?: SanityImageHotspot;

    /**
     * Alt-tekst — `string`
     *
     * Beskriv bildet for skjermlesere
     */
    title?: string;
  };
}

/**
 * Navigation
 *
 *
 */
export interface DsNavigation extends SanityDocument {
  _type: "ds_navigation";

  /**
   * Designsystem navigajsons-struktur — `string`
   *
   *
   */
  title?: string;

  /**
   * Header linker — `array`
   *
   *
   */
  headings?: Array<SanityKeyed<DsNavigationHeading>>;
}

/**
 * Komponentoversikt
 *
 *
 */
export interface DsComponentOverview extends SanityDocument {
  _type: "ds_component_overview";

  /**
   * Komponent — `array`
   *
   *
   */
  components?: Array<
    SanityKeyed<{
      _type: "component";
      /**
       * Komponentnavn — `string`
       *
       *
       */
      title?: string;

      /**
       * Pakkenavn — `reference`
       *
       * Kobler komponenten til en pakke og da om den er core/intern/navno. Alle tilgjengelige valg ligge under <Kodepakker>
       */
      linked_package?: SanityReference<DsPackage>;

      /**
       * Er komponenten ny? — `boolean`
       *
       *
       */
      new?: boolean;

      /**
       * Er komponenten i Figma/designet? — `boolean`
       *
       *
       */
      in_design?: boolean;

      /**
       * Figma bibliotek — `string`
       *
       *
       */
      figma_version?: "new" | "old" | "beta";

      /**
       * Er komponenten Kodet? — `boolean`
       *
       *
       */
      in_code?: boolean;

      /**
       * Er komponenten fortsatt i Beta? — `boolean`
       *
       *
       */
      in_code_beta?: boolean;

      /**
       * Er komponentkoden i synk med Figma? — `boolean`
       *
       *
       */
      figma_sync?: boolean;

      /**
       * Er komponenten i dokumentert? — `boolean`
       *
       *
       */
      in_doc?: boolean;

      /**
       * Legger til link til dokumentasjonen — `reference`
       *
       *
       */
      doc_link?: SanityReference<
        DsComponentPage | KomponentArtikkel | DsArtikkel
      >;
    }>
  >;
}

/**
 * Kodepakke
 *
 *
 */
export interface DsPackage extends SanityDocument {
  _type: "ds_package";

  /**
   * Navn — `string`
   *
   *
   */
  title?: string;

  /**
   * Status — `string`
   *
   *
   */
  status?: "beta" | "live" | "alpha";

  /**
   * Scope — `string`
   *
   *
   */
  scope?: "core" | "internal" | "navno";

  /**
   * Github-kode — `url`
   *
   *
   */
  github_link?: string;
}

/**
 * Komponentartikkel BETA
 *
 *
 */
export interface KomponentArtikkel extends SanityDocument {
  _type: "komponent_artikkel";

  /**
   * Bidragsytere — `array`
   *
   * Legg til de som har bidratt med denne siden!
   */
  contributors?: Array<SanityKeyedReference<Editor>>;

  /**
   * Sidetittel — `string`
   *
   * Bruk en kort og konsis tittel om mulig. Blir satt som `<H1 />` på toppen av siden i URL.
   */
  heading?: string;

  /**
   * url — `slug`
   *
   * Strukturen bestemmes ikke av URL-en
   */
  slug?: { _type: "slug"; current: string };

  /**
   * Bruk — `array`
   *
   *
   */
  content_bruk?: Array<
    | SanityKeyed<GeneriskSeksjon>
    | SanityKeyed<IntroKomponentSeksjon>
    | SanityKeyed<LiveDemoSeksjon>
    | SanityKeyed<UuSeksjon>
    | SanityKeyed<AnatomiSeksjon>
    | SanityKeyed<Tips>
    | SanityKeyed<RelatertInnhold>
  >;

  /**
   * Kode — `array`
   *
   *
   */
  content_kode?: Array<
    | SanityKeyed<GeneriskSeksjon>
    | SanityKeyed<InstallasjonSeksjon>
    | SanityKeyed<PropsSeksjon>
    | SanityKeyed<Tips>
    | SanityKeyed<RelatertInnhold>
  >;

  /**
   * Koblet kodepakke — `reference`
   *
   * Kobler komponenten til en pakke
   */
  linked_package?: SanityReference<DsPackage>;

  /**
   * Figma lenke (optional) — `url`
   *
   *
   */
  figma_link?: string;

  /**
   * Tilbakemeldinger — `object`
   *
   *
   */
  metadata_feedback?: {
    _type: "metadata_feedback";
    /**
     * Skjul artikkel feedback modul — `boolean`
     *
     * Gjemmer <<Var denne artikkelen til hjelp?>> modulen.
     */
    hide_feedback?: boolean;
  };
}

/**
 * Artikkel
 *
 *
 */
export interface DsArtikkel extends SanityDocument {
  _type: "ds_artikkel";

  /**
   * Bidragsytere — `array`
   *
   * Legg til de som har bidratt med denne siden!
   */
  contributors?: Array<SanityKeyedReference<Editor>>;

  /**
   * Sidetittel — `string`
   *
   * Bruk en kort og konsis tittel om mulig. Blir satt som `<H1 />` på toppen av siden i URL.
   */
  heading?: string;

  /**
   * url — `slug`
   *
   * Strukturen bestemmes ikke av URL-en
   */
  slug?: { _type: "slug"; current: string };

  /**
   * Bruk Tabs — `boolean`
   *
   *
   */
  artikkel_type?: boolean;

  /**
   * Innhold — `array`
   *
   *
   */
  innhold?: Array<
    | SanityKeyed<GeneriskSeksjon>
    | SanityKeyed<{
        _type: "riktekst_blokk";
        /**
         * Riktekst — `riktekst`
         *
         *
         */
        body?: Riktekst;
      }>
    | SanityKeyed<Tips>
    | SanityKeyed<RelatertInnhold>
    | SanityKeyed<SpesialSeksjon>
  >;

  /**
   * Innhold i Tabs — `array`
   *
   *
   */
  innhold_tabs?: Array<
    SanityKeyed<{
      _type: "tab";
      /**
       * Tittel — `string`
       *
       * Innhold vil da legges under url/tab-tittel
       */
      title?: string;

      /**
       * Innhold — `array`
       *
       *
       */
      innhold?: Array<
        | SanityKeyed<GeneriskSeksjon>
        | SanityKeyed<{
            _type: "riktekst_blokk";
            /**
             * Riktekst — `riktekst`
             *
             *
             */
            body?: Riktekst;
          }>
        | SanityKeyed<Tips>
        | SanityKeyed<RelatertInnhold>
      >;
    }>
  >;

  /**
   * Tilbakemeldinger — `object`
   *
   *
   */
  metadata_feedback?: {
    _type: "metadata_feedback";
    /**
     * Skjul artikkel feedback modul — `boolean`
     *
     * Gjemmer <<Var denne artikkelen til hjelp?>> modulen.
     */
    hide_feedback?: boolean;
  };
}

/**
 * Aksel Artikkel
 *
 *
 */
export interface AkselArtikkel extends SanityDocument {
  _type: "aksel_artikkel";

  /**
   * Redaktører — `array`
   *
   * Øverste redaktør vil vises med navn på artikkel
   */
  contributors?: Array<SanityKeyedReference<Editor>>;

  /**
   * Sidetittel — `string`
   *
   * Bruk en kort og konsis tittel om mulig. Blir satt som `<H1 />` på toppen av siden i URL.
   */
  heading?: string;

  /**
   * url — `slug`
   *
   *
   */
  slug?: { _type: "slug"; current: string };

  /**
   * Tema — `array`
   *
   * Legg til de viktigeste temaene
   */
  tema?: Array<SanityKeyedReference<AkselTema>>;

  /**
   * Kort Intro/Oppsummering — `string`
   *
   * Brukes i kort og innganger
   */
  oppsummering?: string;

  /**
   * Innhold — `array`
   *
   *
   */
  innhold?: Array<
    | SanityKeyed<GeneriskSeksjonArtikkel>
    | SanityKeyed<{
        _type: "riktekst_blokk";
        /**
         * Riktekst — `riktekst`
         *
         *
         */
        body?: Riktekst;
      }>
    | SanityKeyed<Tips>
    | SanityKeyed<RelatertInnhold>
  >;

  /**
   * Banner — `object`
   *
   *
   */
  banner?: {
    _type: "banner";
    /**
     * Variant — `string`
     *
     *
     */
    variant?: "standard" | "bilde";

    /**
     * Banner-bilde — `image`
     *
     *
     */
    banner_img?: {
      _type: "image";
      asset: SanityReference<SanityImageAsset>;
      crop?: SanityImageCrop;
      hotspot?: SanityImageHotspot;

      /**
       * Alt-tekst — `string`
       *
       *
       */
      alt?: string;
    };
  };

  /**
   * Tilbakemeldinger — `object`
   *
   *
   */
  metadata_feedback?: {
    _type: "metadata_feedback";
    /**
     * Skjul artikkel feedback modul — `boolean`
     *
     * Gjemmer <<Var denne artikkelen til hjelp?>> modulen.
     */
    hide_feedback?: boolean;
  };
}

/**
 * Blogg
 *
 *
 */
export interface AkselBlogg extends SanityDocument {
  _type: "aksel_blogg";

  /**
   * Redaktører — `array`
   *
   * Øverste redaktør vil vises med navn på artikkel
   */
  contributors?: Array<SanityKeyedReference<Editor>>;

  /**
   * Sidetittel — `string`
   *
   * Bruk en kort og konsis tittel om mulig. Blir satt som `<H1 />` på toppen av siden i URL.
   */
  heading?: string;

  /**
   * url — `slug`
   *
   *
   */
  slug?: { _type: "slug"; current: string };

  /**
   * Kort Intro/Oppsummering — `string`
   *
   * Brukes i kort og innganger
   */
  oppsummering?: string;

  /**
   * Innhold — `array`
   *
   *
   */
  innhold?: Array<
    | SanityKeyed<GeneriskSeksjonArtikkel>
    | SanityKeyed<{
        _type: "riktekst_blokk";
        /**
         * Riktekst — `riktekst`
         *
         *
         */
        body?: Riktekst;
      }>
    | SanityKeyed<Tips>
    | SanityKeyed<RelatertInnhold>
  >;

  /**
   * Banner — `object`
   *
   *
   */
  banner?: {
    _type: "banner";
    /**
     * Variant — `string`
     *
     *
     */
    variant?: "standard" | "bilde";

    /**
     * Banner-bilde — `image`
     *
     *
     */
    banner_img?: {
      _type: "image";
      asset: SanityReference<SanityImageAsset>;
      crop?: SanityImageCrop;
      hotspot?: SanityImageHotspot;

      /**
       * Alt-tekst — `string`
       *
       *
       */
      alt?: string;
    };
  };

  /**
   * Tilbakemeldinger — `object`
   *
   *
   */
  metadata_feedback?: {
    _type: "metadata_feedback";
    /**
     * Skjul artikkel feedback modul — `boolean`
     *
     * Gjemmer <<Var denne artikkelen til hjelp?>> modulen.
     */
    hide_feedback?: boolean;
  };
}

/**
 * Aksel Tema
 *
 *
 */
export interface AkselTema extends SanityDocument {
  _type: "aksel_tema";

  /**
   * Navn — `string`
   *
   *
   */
  title?: string;

  /**
   * Kort Intro/Oppsummering — `string`
   *
   * Brukes i kort og innganger
   */
  oppsummering?: string;

  /**
   * Beskrivelse — `riktekst`
   *
   *
   */
  beskrivelse?: Riktekst;

  /**
   * Seksjonering (optional) (Ikke i prod enda) — `array`
   *
   * Del inn artiklene i flere seksjoner
   */
  seksjoner?: Array<
    SanityKeyed<{
      _type: "seksjon";
      /**
       * Tittel — `string`
       *
       *
       */
      title?: string;

      /**
       * Beskrivelse — `riktekst`
       *
       *
       */
      beskrivelse?: Riktekst;

      /**
       * Sider — `array`
       *
       *
       */
      sider?: Array<SanityKeyedReference<AkselArtikkel>>;
    }>
  >;
}

/**
 * Quotes
 *
 *
 */
export interface Quotes extends SanityDocument {
  _type: "quotes";

  /**
   * Quotes — `array`
   *
   *
   */
  quotes?: Array<
    SanityKeyed<{
      _type: "list";
      /**
       * Quote — `string`
       *
       *
       */
      title?: string;

      /**
       * Kilde — `string`
       *
       *
       */
      kilde?: string;
    }>
  >;
}

export type GeneriskSeksjon = {
  _type: "generisk_seksjon";
  /**
   * Tittel (h2) — `string`
   *
   *
   */
  title?: string;

  /**
   * Innhold — `array`
   *
   *
   */
  brikker?: Array<
    | SanityKeyed<{
        _type: "riktekst_blokk";
        /**
         * Riktekst — `riktekst`
         *
         *
         */
        body?: Riktekst;
      }>
    | SanityKeyed<Tips>
    | SanityKeyed<RelatertInnhold>
    | SanityKeyed<DoDontV2>
    | SanityKeyed<Bilde>
    | SanityKeyed<Video>
    | SanityKeyed<AlertV2>
    | SanityKeyed<Kode>
    | SanityKeyedReference<DsCodeExample>
    | SanityKeyed<Tabell>
    | SanityKeyed<AccordionV2>
    | SanityKeyed<SpesialSeksjon>
  >;
};

export type GeneriskSeksjonArtikkel = {
  _type: "generisk_seksjon_artikkel";
  /**
   * Tittel (h2) — `string`
   *
   *
   */
  title?: string;

  /**
   * Innhold — `array`
   *
   *
   */
  brikker?: Array<
    | SanityKeyed<{
        _type: "riktekst_blokk";
        /**
         * Riktekst — `riktekst`
         *
         *
         */
        body?: Riktekst;
      }>
    | SanityKeyed<Tips>
    | SanityKeyed<RelatertInnhold>
    | SanityKeyed<DoDontV2>
    | SanityKeyed<Bilde>
    | SanityKeyed<Video>
    | SanityKeyed<AlertV2>
    | SanityKeyed<Kode>
    | SanityKeyed<Tabell>
    | SanityKeyed<AccordionV2>
  >;
};

export type Riktekst = Array<SanityKeyed<SanityBlock>>;

export type DoDontV2 = {
  _type: "do_dont_v2";
  /**
   * Tittel (h3) — `string`
   *
   *
   */
  title?: string;

  /**
   * Forklaring (optional) — `riktekst`
   *
   *
   */
  forklaring?: Riktekst;

  /**
   * Do / donts — `array`
   *
   *
   */
  blokker?: Array<SanityKeyed<DoDontBlock>>;
};

export type Bilde = {
  _type: "bilde";
  asset: SanityReference<SanityImageAsset>;
  crop?: SanityImageCrop;
  hotspot?: SanityImageHotspot;

  /**
   * Alt-tekst — `string`
   *
   * Beskriv bildet for skjermlesere
   */
  alt?: string;

  /**
   * hide_floating — `boolean`
   *
   *
   */
  hide_floating?: boolean;

  /**
   * Bilde med flytende tekst rundt — `boolean`
   *
   * Dette feltet fungerer ikke lengre, bruk et vanlig bilde uten flytende tekst
   */
  floating?: boolean;

  /**
   * Bilde-tekst (optional) — `string`
   *
   * Dette vil stå under bildet
   */
  caption?: string;

  /**
   * Plassering av bilde — `string`
   *
   *
   */
  floating_align?: "venstre" | "hoyre";

  /**
   * Flytende tekst — `riktekst`
   *
   *
   */
  floating_text?: Riktekst;

  /**
   * Bildet tar bare ~halve bredden — `boolean`
   *
   *
   */
  small?: boolean;
};

export type RiktekstEnkel = Array<SanityKeyed<SanityBlock>>;

export type AlertV2 = {
  _type: "alert_v2";
  /**
   * Variant — `string`
   *
   *
   */
  variant?: "success" | "info" | "warning" | "error";

  /**
   * Heading (optional) — `string`
   *
   *
   */
  heading?: string;

  /**
   * Heading nivå — `string`
   *
   *
   */
  heading_level?: "h3" | "h4";

  /**
   * Innhold — `riktekst_enkel`
   *
   *
   */
  body?: RiktekstEnkel;
};

export type Kode = {
  _type: "kode";
  /**
   * Bruk predefinert kodesnutt? — `boolean`
   *
   *
   */
  variant?: boolean;

  /**
   * Predefinert kodesnutt — `reference`
   *
   *
   */
  ref?: SanityReference<DsCodeExample>;

  /**
   * Kode — `code`
   *
   *
   */
  code?: Code;
};

export type RelatertInnhold = {
  _type: "relatert_innhold";
  /**
   * Lenker til innhold — `array`
   *
   *
   */
  lenker?: Array<
    SanityKeyed<{
      _type: "lenke";
      /**
       * Tittel — `string`
       *
       *
       */
      title?: string;

      /**
       * Beskrivelse — `string`
       *
       *
       */
      description?: string;

      /**
       * Intern side i Sanity — `boolean`
       *
       *
       */
      intern?: boolean;

      /**
       * Lenke til Intern sanity-side — `reference`
       *
       *
       */
      intern_lenke?: SanityReference<
        | DsComponentPage
        | KomponentArtikkel
        | DsArtikkel
        | AkselArtikkel
        | AkselBlogg
      >;

      /**
       * Lenke til ekstern side — `url`
       *
       *
       */
      ekstern_link?: string;

      /**
       * Linker til et eksternt domene — `boolean`
       *
       *
       */
      ekstern_domene?: boolean;

      /**
       * Tagging — `string`
       *
       *
       */
      tags?: "none" | "custom";

      /**
       * Tag — `string`
       *
       *
       */
      tag?: string;
    }>
  >;
};

export type IntroKomponentSeksjon = {
  _type: "intro_komponent_seksjon";
  /**
   * Intro/Ingress — `riktekst_enkel`
   *
   *
   */
  body?: RiktekstEnkel;

  /**
   * Egnet til — `array`
   *
   *
   */
  brukes_til?: Array<SanityKeyed<string>>;

  /**
   * Når bør man vurdere noe annet (optional) — `array`
   *
   *
   */
  brukes_ikke_til?: Array<SanityKeyed<string>>;
};

export type LiveDemoSeksjon = {
  _type: "live_demo_seksjon";
  /**
   * Avsnitt (optional) — `riktekst_enkel`
   *
   *
   */
  body?: RiktekstEnkel;

  /**
   * Erstatt Sandbox med vanlig kode-eksempel — `boolean`
   *
   *
   */
  erstatt?: boolean;

  /**
   * Demo/Sandobox — `reference`
   *
   *
   */
  sandbox_ref?: SanityReference<DsCodeSandbox>;

  /**
   * Kode-eksempel — `reference`
   *
   *
   */
  code_ref?: SanityReference<DsCodeExample>;
};

export type Tabell = {
  _type: "tabell";
  /**
   * Tittel (optional) — `string`
   *
   * Gi tabellen et navn for å lettere finne den
   */
  title?: string;

  /**
   * Tabell — `powerTable`
   *
   *
   */
  powerTable?: PowerTable;
};

export type UuSeksjon = {
  _type: "uu_seksjon";
  /**
   * Tittel (h2) — `string`
   *
   *
   */
  title?: string;

  /**
   * Interaksjon med mus (optional) — `riktekst_enkel`
   *
   *
   */
  interaksjon_mus?: RiktekstEnkel;

  /**
   * Interaksjon med touch (optional) — `riktekst_enkel`
   *
   *
   */
  interaksjon_touch?: RiktekstEnkel;

  /**
   * Interaksjon med tastatur (optional) — `riktekst_enkel`
   *
   * Ekstra info som ikke kan forklares med key + action under
   */
  interaksjon_tastatur?: RiktekstEnkel;

  /**
   * Tastatur key + action — `array`
   *
   *
   */
  tastatur?: Array<
    SanityKeyed<{
      _type: "keys";
      /**
       * key — `string`
       *
       *
       */
      key?: string;

      /**
       * action — `string`
       *
       *
       */
      action?: string;
    }>
  >;

  /**
   * Interaksjon med skjermleser (optional) — `riktekst_enkel`
   *
   *
   */
  interaksjon_skjermleser?: RiktekstEnkel;
};

export type AnatomiSeksjon = {
  _type: "anatomi_seksjon";
  /**
   * Nested — `boolean`
   *
   *
   */
  nested?: boolean;

  /**
   * Tittel (h2) — `string`
   *
   *
   */
  title?: string;

  /**
   * Intro (optional) — `riktekst`
   *
   *
   */
  intro?: Riktekst;

  /**
   * Anatomi-bilde — `bilde`
   *
   *
   */
  bilde?: Bilde;

  /**
   * Forklaring — `array`
   *
   * Forklar annoteringen av anatomi-bildet
   */
  forklaring?: Array<
    SanityKeyed<{
      _type: "liste_element";
      /**
       * Element — `string`
       *
       *
       */
      element?: string;

      /**
       * Beskrivelse (optional) — `riktekst_enkel`
       *
       *
       */
      beskrivelse?: RiktekstEnkel;
    }>
  >;

  /**
   * Ekstra anatomi-paneler (optional) — `array`
   *
   * Kan legge til flere anatomi-paneler under samme Anatomi-heading
   */
  extra?: Array<
    SanityKeyed<{
      _type: "anatomi_seksjon";
      /**
       * Nested — `boolean`
       *
       *
       */
      nested?: boolean;

      /**
       * Tittel (h2) — `string`
       *
       *
       */
      title?: string;

      /**
       * Intro (optional) — `riktekst`
       *
       *
       */
      intro?: Riktekst;

      /**
       * Anatomi-bilde — `bilde`
       *
       *
       */
      bilde?: Bilde;

      /**
       * Forklaring — `array`
       *
       * Forklar annoteringen av anatomi-bildet
       */
      forklaring?: Array<
        SanityKeyed<{
          _type: "liste_element";
          /**
           * Element — `string`
           *
           *
           */
          element?: string;

          /**
           * Beskrivelse (optional) — `riktekst_enkel`
           *
           *
           */
          beskrivelse?: RiktekstEnkel;
        }>
      >;
    }>
  >;
};

export type InstallasjonSeksjon = {
  _type: "installasjon_seksjon";
  /**
   * Tittel (h2) — `string`
   *
   *
   */
  title?: string;

  /**
   * Installasjon-snippet — `reference`
   *
   *
   */
  code_ref?: SanityReference<DsCodeExample>;
};

export type PropsSeksjon = {
  _type: "props_seksjon";
  /**
   * Tittel (h2) — `string`
   *
   *
   */
  title?: string;

  /**
   * Elementer — `array`
   *
   *
   */
  elementer?: Array<SanityKeyed<PropTable>>;

  /**
   * Props — `array`
   *
   *
   */
  komponenter?: Array<
    SanityKeyed<{
      _type: "komponent";
      /**
       * Komponent navn — `string`
       *
       * Slik man ville brukt den, eks Accordion.Item
       */
      title?: string;

      /**
       * Bruker komponenten OverridableComponent API-et — `boolean`
       *
       *
       */
      overridable?: boolean;

      /**
       * Komponent referanse — `reference`
       *
       *
       */
      propref?: SanityReference<DsProps>;
    }>
  >;
};

export type AccordionV2 = {
  _type: "accordion_v2";
  /**
   * Tittel (optional) — `string`
   *
   *
   */
  title?: string;

  /**
   * Accordions — `array`
   *
   *
   */
  list?: Array<
    SanityKeyed<{
      _type: "element";
      /**
       * Tittel  — `string`
       *
       *
       */
      title?: string;

      /**
       * Innhold — `array`
       *
       *
       */
      innhold?: Array<
        | SanityKeyed<{
            _type: "riktekst_blokk";
            /**
             * Riktekst — `riktekst`
             *
             *
             */
            body?: Riktekst;
          }>
        | SanityKeyed<Tips>
        | SanityKeyed<RelatertInnhold>
        | SanityKeyed<DoDontV2>
        | SanityKeyed<Bilde>
        | SanityKeyed<Video>
        | SanityKeyed<AlertV2>
        | SanityKeyed<Kode>
        | SanityKeyed<Tabell>
      >;
    }>
  >;
};

export type RiktekstTabell = Array<SanityKeyed<SanityBlock>>;

export type SpesialSeksjon = {
  _type: "spesial_seksjon";
  /**
   * Modul — `string`
   *
   *
   */
  modul?: "farge_kategori" | "ikonsok" | "endringslogg" | "komponentoversikt";

  /**
   * Farge kategori — `reference`
   *
   *
   */
  farge_ref?: SanityReference<DsColorCategories>;
};

export type Video = {
  _type: "video";
  /**
   * Video i WebM format — `file`
   *
   * Vi anbefaler å bruke Webm formatet om mulig!
   */
  webm?: { _type: "file"; asset: SanityReference<any> };

  /**
   * Video i Mp4 format (fallback) — `file`
   *
   *
   */
  fallback?: { _type: "file"; asset: SanityReference<any> };

  /**
   * Alt tekst for skjermlesere — `string`
   *
   *
   */
  alt?: string;

  /**
   * Videotekst — `string`
   *
   * Kort beskrivelse som vises rett under videon
   */
  caption?: string;

  /**
   * Transkripsjon — `text`
   *
   * Hvis videoen inneholder lyd, anbelfaler vi å skrive en transkripsjon som kan leses under videoen.
   */
  transkripsjon?: string;
};

export type NavigationLink = {
  _type: "navigation_link";
  /**
   * Tittel — `string`
   *
   *
   */
  title?: string;

  /**
   * Link — `reference`
   *
   *
   */
  link_ref?: SanityReference<DsComponentPage | KomponentArtikkel | DsArtikkel>;
};

export type NavigationDropdown = {
  _type: "navigation_dropdown";
  /**
   * Tittel — `string`
   *
   *
   */
  title?: string;

  /**
   * Meny — `array`
   *
   *
   */
  dropdown?: Array<
    SanityKeyed<NavigationLink> | SanityKeyed<NavigationDropdown>
  >;
};

export type Alert = {
  _type: "alert";
  /**
   * Variant — `string`
   *
   *
   */
  variant?: "success" | "info" | "warning" | "error";

  /**
   * Størrelse — `string`
   *
   *
   */
  size?: "medium" | "small";

  /**
   * Heading (optional) — `string`
   *
   *
   */
  heading?: string;

  /**
   * Heading nivå — `string`
   *
   *
   */
  heading_level?: "h2" | "h3" | "h4";

  /**
   * Innhold — `riktekst_enkel`
   *
   *
   */
  body?: RiktekstEnkel;
};

export type CodeExampleRef = {
  _type: "code_example_ref";
  /**
   * Kode eksempel — `reference`
   *
   *
   */
  ref?: SanityReference<DsCodeExample>;
};

export type CodeSandboxRef = {
  _type: "code_sandbox_ref";
  /**
   * Sandbox — `reference`
   *
   *
   */
  ref?: SanityReference<DsCodeSandbox>;
};

export type CodeSnippet = {
  _type: "code_snippet";
  /**
   * Tittel (for preview internt i sanity) — `string`
   *
   *
   */
  title?: string;

  /**
   * Kode — `code`
   *
   *
   */
  code?: Code;
};

export type DoDont = {
  _type: "do_dont";
  /**
   * Tittel (vises bare internt i sanity) — `string`
   *
   *
   */
  title?: string;

  /**
   * Do / donts — `array`
   *
   * Liste med do/donts
   */
  blocks?: Array<SanityKeyed<DoDontBlock>>;
};

export type DoDontBlock = {
  _type: "do_dont_block";
  /**
   * Fullwidth — `boolean`
   *
   * Tar opp ~ 40% eller 100% av tilgjengelig bredde
   */
  fullwidth?: boolean;

  /**
   * Bilde — `image`
   *
   *
   */
  picture?: {
    _type: "image";
    asset: SanityReference<SanityImageAsset>;
    crop?: SanityImageCrop;
    hotspot?: SanityImageHotspot;
  };

  /**
   * alt tekst for bilde — `string`
   *
   *
   */
  alt?: string;

  /**
   * Fritekst — `text`
   *
   * Korte konsise beskrivelser. Bruk fullbredde bilde i dodont med egen tekst for lengre forklaringer
   */
  description?: string;

  /**
   * Variant — `string`
   *
   *
   */
  variant?: "do" | "dont" | "warning";
};

export type Picture = {
  _type: "picture";
  asset: SanityReference<SanityImageAsset>;
  crop?: SanityImageCrop;
  hotspot?: SanityImageHotspot;

  /**
   * Alt-tekst — `string`
   *
   * Beskriv bildet for skjermlesere
   */
  title?: string;

  /**
   * Bilde-tekst — `string`
   *
   * Dette vil stå under bildet
   */
  caption?: string;
};

export type PictureText = {
  _type: "picture_text";
  asset: SanityReference<SanityImageAsset>;
  crop?: SanityImageCrop;
  hotspot?: SanityImageHotspot;

  /**
   * Alt-tekst — `string`
   *
   * Beskriv bildet for skjermlesere
   */
  title?: string;

  /**
   * Bilde plassering — `string`
   *
   *
   */
  placement?: "right" | "left";

  /**
   * Innhold — `riktekst_enkel`
   *
   *
   */
  body?: RiktekstEnkel;
};

export type PropTable = {
  _type: "prop_table";
  /**
   * Komponent navn — `string`
   *
   *
   */
  title?: string;

  /**
   * children-prop required av type React.ReactNode — `boolean`
   *
   *
   */
  preset_children?: boolean;

  /**
   * className-prop — `boolean`
   *
   *
   */
  preset_classname?: boolean;

  /**
   * Props — `array`
   *
   * Liste med props, tilsvarer en rad i tabellen
   */
  props?: Array<SanityKeyed<PropTableProp>>;

  /**
   * Bruker OverridableComponent — `boolean`
   *
   *
   */
  overridable?: boolean;

  /**
   * Hvor settes ref — `string`
   *
   * Eks: root element
   */
  refplacement?: string;

  /**
   * Hvilken props ekstender komponent-props — `string`
   *
   * Eks: HtmlDivElement, ButtonProps
   */
  extends?: string;
};

export type PropTableProp = {
  _type: "prop_table_prop";
  /**
   * Name — `string`
   *
   *
   */
  name?: string;

  /**
   * Type — `string`
   *
   *
   */
  type?: string;

  /**
   * Beskrivelse (optional) — `string`
   *
   *
   */
  description?: string;

  /**
   * Default (optional) — `string`
   *
   *
   */
  default?: string;

  /**
   * Required — `boolean`
   *
   *
   */
  required?: boolean;
};

export type RelatedPages = {
  _type: "related_pages";
  /**
   * Sider — `array`
   *
   *
   */
  links?: Array<
    SanityKeyed<{
      _type: "link";
      /**
       * Tittel — `string`
       *
       *
       */
      title?: string;

      /**
       * Beskrivelse — `string`
       *
       *
       */
      description?: string;

      /**
       * Intern side i Sanity — `boolean`
       *
       *
       */
      internal?: boolean;

      /**
       * Lenke til Intern sanity-side — `reference`
       *
       *
       */
      internal_link?: SanityReference<
        | DsComponentPage
        | KomponentArtikkel
        | DsArtikkel
        | AkselArtikkel
        | AkselBlogg
      >;

      /**
       * Lenke til ekstern side — `url`
       *
       *
       */
      external_link?: string;

      /**
       * Tagging — `string`
       *
       * Velg hvordan kortet skal tagges
       */
      tags?: "default" | "main_categories";

      /**
       * Kategori — `reference`
       *
       *
       */
      category_ref?: SanityReference<MainCategories>;
    }>
  >;
};

export type Tips = {
  _type: "tips";
  /**
   * Innhold — `riktekst_enkel`
   *
   *
   */
  body?: RiktekstEnkel;
};

export type BlockContent = Array<
  | SanityKeyed<SanityBlock>
  | SanityKeyed<Picture>
  | SanityKeyed<PictureText>
  | SanityKeyed<Tips>
  | SanityKeyed<Alert>
  | SanityKeyed<RelatedPages>
  | SanityKeyed<CodeSnippet>
  | SanityKeyed<DoDont>
  | SanityKeyed<CodeSandboxRef>
  | SanityKeyed<CodeExampleRef>
  | SanityKeyed<PropTable>
>;

export type DsColor = {
  _type: "ds_color";
  /**
   * Navn — `string`
   *
   *
   */
  title?: string;

  /**
   * CSS variabelnavn — `string`
   *
   *
   */
  full_title?: string;

  /**
   * Fargetype/nivå — `string`
   *
   *
   */
  color_type?: "global" | "semantic";

  /**
   * Brukt fargenavn — `string`
   *
   *
   */
  color_name?: string;

  /**
   * Fargeroller — `array`
   *
   *
   */
  color_roles?: Array<SanityKeyed<string>>;

  /**
   * Brukt farge — `string`
   *
   *
   */
  color_value?: string;

  /**
   * Fargeindeks — `number`
   *
   * Brukes for å endre rekkefølgen på listen. Farger med indeks 0 vil være først, større tall sorteres under der igjen
   */
  color_index?: number;
};

export type DsNavigationHeading = {
  _type: "ds_navigation_heading";
  /**
   * Heading tittel — `string`
   *
   *
   */
  title?: string;

  /**
   * Hovedkategori — `reference`
   *
   *
   */
  category_ref?: SanityReference<MainCategories>;

  /**
   * Side selve headingen linker til — `reference`
   *
   * Husk å legge denne til i menyen også, hvis ikke blir den bare tilgjengelig via headern
   */
  link_ref?: SanityReference<DsComponentPage | KomponentArtikkel | DsArtikkel>;

  /**
   * Meny for denne headingen — `array`
   *
   *
   */
  menu?: Array<
    | SanityKeyed<{
        _type: "item";
        /**
         * Menypunkt tittel — `string`
         *
         *
         */
        title?: string;

        /**
         * Link til side — `reference`
         *
         *
         */
        link?: SanityReference<
          DsComponentPage | KomponentArtikkel | DsArtikkel
        >;
      }>
    | SanityKeyed<{
        _type: "subheading";
        /**
         * Subheading — `string`
         *
         *
         */
        title?: string;
      }>
  >;
};

export type CodeExampleExample = {
  _type: "code_example_example";
  /**
   * Tab tittel — `string`
   *
   *
   */
  title?: string;

  /**
   * Kode eksempel — `code`
   *
   *
   */
  example?: Code;
};

export type Documents =
  | VkFrontpage
  | Team
  | Editor
  | Navigation
  | Introduction
  | DsChangelog
  | DsCodeExample
  | DsCodeSandbox
  | DsColorCategories
  | DsProps
  | DsComponentPage
  | DsComponentTemplate
  | DsFrontpage
  | MainCategories
  | DsNavigation
  | DsComponentOverview
  | DsPackage
  | KomponentArtikkel
  | DsArtikkel
  | AkselArtikkel
  | AkselBlogg
  | AkselTema
  | Quotes;

/**
 * This interface is a stub. It was referenced in your sanity schema but
 * the definition was not actually found. Future versions of
 * sanity-codegen will let you type this explicity.
 */
type Code = any;

/**
 * This interface is a stub. It was referenced in your sanity schema but
 * the definition was not actually found. Future versions of
 * sanity-codegen will let you type this explicity.
 */
type PowerTable = any;
