export default {
  title: "Tokens",
  name: "ds_tokens",
  type: "document",
  fields: [
    {
      title: "Navn",
      name: "title",
      type: "string",
      validation: (Rule) => Rule.required(),
      readOnly: true,
    },
    {
      title: "Verdi",
      name: "color",
      type: "string",
      validation: (Rule) => Rule.required(),
      readOnly: true,
    },
    {
      title: "Autogenerert",
      name: "autogenerated",
      type: "boolean",
      readOnly: true,
    },
  ],
};
