import { codeExamplesClient } from ".";
import { ExampleKeys } from "../examples";
import lowerCase from "lodash.lowercase";

import dotenv from "dotenv";

dotenv.config();

const updateExamples = async () => {
  const token = process.env.SANITY_WRITE_KEY;

  ExampleKeys.forEach((key) => {
    codeExamplesClient(token)
      .createIfNotExists({
        _id: `${key}_autogen_example`,
        _type: "ds_code_example",
        infercode: true,
        preview: `https://example.com/examples/${key}`,
        title: lowerCase(key),
        autogenerated: true,
      })
      .then(() => console.log(`Updated kodeexample: ${key}`))
      .catch((e) => console.error(e.message));
  });
};

const deleteRemovedExamples = async () => {
  const token = process.env.SANITY_WRITE_KEY;
  const query = `*[_type == "ds_code_example"]`;
  const docs = await codeExamplesClient(token).fetch(query);

  docs.forEach((doc) => {
    if (!ExampleKeys.includes(doc._id.replace("_autogen_example", ""))) {
      codeExamplesClient(token)
        .delete(doc._id)
        .then(() => console.log(`Deleted ${doc._id}`))
        .catch((e) => {
          throw e;
        });
    }
  });
};

const main = async () => {
  await deleteRemovedExamples();

  await updateExamples();
};

main();
