import { SandboxKeys } from "../../stories/sandbox";
import dotenv from "dotenv";
import { noCdnClient } from "../sanity/sanity.server";
dotenv.config();
const token = process.env.SANITY_WRITE_KEY;

const main = async () => {
  /* const transactionClient = noCdnClient(token).transaction();

  const docs = await noCdnClient(token).fetch(`*[_type == "ds_code_sandbox"]`); */
  /* transactionClient.createIfNotExists({
    _id: `${key}_autogen_sandbox`,
    _type: "ds_code_sandbox",
    title: key,
    autogenerated: true,
  }); */
  /* await transactionClient
    .commit()
    .then(() => console.log(`Updated code-sandboxes`))
    .catch((e) => console.error(e.message)); */
};

main();
