import { Download } from "@navikt/ds-icons";
import React from "react";

export default {
  title: "Installasjon",
  name: "installasjon_seksjon",
  type: "object",
  fields: [
    {
      title: "Tittel (h2)",
      name: "title",
      type: "string",
      initialValue: "Installasjon",
      readOnly: true,
    },
    {
      title: "Installasjon-snippet",
      name: "code_ref",
      type: "reference",
      to: [{ type: "ds_code_example" }],
      options: {
        filter: "autogenerated != true",
      },
      validation: (Rule) =>
        Rule.required().error("Må velge en installasjons-snippet"),
    },
  ],
  preview: {
    prepare() {
      return {
        title: "Installasjon",
        media: () => <Download />,
      };
    },
  },
};
