import { noCdnClient } from "..";
import { ExampleKeys } from "../../stories/examples";
import { SandboxKeys } from "../../stories/sandbox";
import startCase from "lodash.startcase";
import dotenv from "dotenv";
dotenv.config();

type ExampleT = {
  _id: string;
  refs: number;
  autogenerated: boolean;
  _type: string;
};

const main = async () => {
  const token = process.env.SANITY_WRITE_KEY;

  const exampleKeys = [...ExampleKeys].map((x) =>
    startCase(x).replaceAll(" ", "")
  );

  const sandboxKeys = [...SandboxKeys].map((x) =>
    startCase(x).replaceAll(" ", "")
  );

  const docs: ExampleT[] = await noCdnClient(token).fetch(
    `*[_type in ["ds_code_example", "ds_code_sandbox"]]{
      _id,
      _type,
      autogenerated,
      "refs": count(*[references(^._id)])
    }`
  );

  const unused = docs.filter((x) => x.refs === 0 && x.autogenerated);
  const sandboxes = unused
    .filter((x) => x._type === "ds_code_sandbox")
    .map((x) => startCase(x._id.split("_")[0]).replaceAll(" ", ""));
  const examples = unused
    .filter((x) => x._type === "ds_code_example")
    .map((x) => startCase(x._id.split("_")[0]).replaceAll(" ", ""));

  console.group("Ubrukte eksempler");
  if (sandboxes.length) {
    console.group("Sandboxes");
    console.log(
      sandboxes
        .map((x) => `${sandboxKeys.includes(x) ? "🗑️ " : "🚀"}  ${x}`)
        .join("\n")
    );
    console.groupEnd();
  }
  if (examples.length) {
    console.group("Examples");
    console.log(
      examples
        .map((x) => `${exampleKeys.includes(x) ? "🗑️ " : "🚀"}  ${x}`)
        .join("\n")
    );
    console.groupEnd();
  }
  if (!(sandboxes.length && examples.length)) {
    console.log("Alt er ryddet!");
  }
  console.groupEnd();
};

main();
