import { DsCodeExample } from "..";
import { ExampleKeys } from "../../stories/examples";
import lowerCase from "lodash/lowerCase";
import dotenv from "dotenv";
import { noCdnClient } from "../sanity/sanity.server";
dotenv.config();

const main = async () => {
  const token = process.env.SANITY_WRITE_KEY;
  const transactionClient = noCdnClient(token).transaction();

  const docs: DsCodeExample[] = await noCdnClient(token).fetch(
    `*[_type == "ds_code_example"]`
  );

  for (const doc of docs) {
    if (
      doc.autogenerated &&
      !ExampleKeys.includes(doc._id.replace("_autogen_example", ""))
    ) {
      transactionClient.delete(doc._id);
    }
  }

  for (const key of ExampleKeys) {
    transactionClient.createIfNotExists({
      _id: `${key}_autogen_example`,
      _type: "ds_code_example",
      infercode: true,
      preview: `https://example.com/examples/${key}`,
      title: lowerCase(key),
      autogenerated: true,
    });
  }
  await transactionClient
    .commit()
    .then(() => console.log(`Updated code-examples`))
    .catch((e) => console.error(e.message));
};

main();
